version: '3'
services:
  app:
    build: .

  db:
    image: mysql:8.0
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

